package com.aim.project.ssp.interfaces;

import java.util.ArrayList;

import com.aim.project.ssp.instance.InitialisationMode;
import com.aim.project.ssp.instance.Location;
import com.aim.project.ssp.solution.SSPSolution;

/**
 * @author Warren G. Jackson
 * @since 17/03/2025
 *
 */
public interface SSPInstanceInterface {

	/**
	 *
	 * @param mode Specifies one of the initialisation modes.
	 * @return A complete solution generated by one of RANDOM or CONSTRUCTIVE initialisation methods.
	 */
	public SSPSolution createSolution(InitialisationMode mode);
	
	public ObjectiveFunctionInterface getSSPObjectiveFunction();
	
	public int getNumberOfLocations();
	
	public Location getSightseeingLocation(int iDeliveryId);
	
	public Location getHotelLocation();
	
	public Location getAirportLocation();
	
	public ArrayList<Location> getSolutionAsListOfLocations(SSPSolutionInterface oSolution);
}
